repos:
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: python -m flake8
        args: ['--max-line-length=100', '--ignore=E203,W503']
        language: system
        types: [python]
      - id: mypy
        name: mypy 
        entry: python -m mypy
        args: [--cache-dir=/dev/null]
        language: system
        types: [python]
        additional_dependencies: ['mypy:1.24']
        language_version: 3.6.0
