#repos:
  #- repo: local
    #hooks:
      #- id: flake8
        #name: flake8
        #entry: python -m flake8
        #args: ['--max-line-length=100', '--ignore=E203,W503']
        #language: system
        #types: [python]
      #- id: mypy
        #name: mypy 
        #entry: python -m mypy
        #args: [--cache-dir=/dev/null]
        #language: system
        #types: [python]
        #additional_dependencies: ['mypy:1.24']
        #language_version: 3.6.0
repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
      - id: flake8
        args: ['--max-line-length=100', '--ignore=E203,W503']
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.790
    hooks:
      - id: mypy
        args: [--cache-dir=/dev/null]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.1.2
    hooks:
      - id: prettier
        types: [python]
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.6.4
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v2.6.0
    hooks:
      - id: pylint
