git:
  - depth: false
language: python            
jobs:
  include:
    - name: "Python 3.8.0 on Xenial Linux"
      python: 3.8           
script: 
  - pre-commit run --all-files
cache:
    directories:
        - $HOME/.cache/pre-commit
