git:
  - depth: false
language: python            
jobs:
  include:
    - name: "Python 3.8.0 on Xenial Linux"
      python: 3.8           
install: 
  - pip3 install --upgrade pip 
script: 
  - pre-commit run --all-files
  - python3 test.py || python test.py
cache:
    directories:
        - $HOME/.cache/pip
        - $HOME/.cache/pre-commit
