version: 2.1
orbs:
    win: circleci/windows@2.2.0

jobs:
  one:
    docker:
      - image: circleci/ruby:2.4.1
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: echo "A first hello"
      - run: sleep 15
  windows-test:
    executor:
      name: win/default
      size: "medium" 

    steps:
      - checkout
      - run: Write-Host 'Hello, Windows'
workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - windows-test
